/* DEA quiz question bank.
   Source key: B1 = Course book pages 1-52, B2 = pages 53-102, B3 = pages 105-156, CL = Portfolio checklist.
   Add a question by copying an entry. "a" is the index (0-3) of the correct option in "o".
   Options are shuffled each time the question is shown. */
const SRC = {
  B1: n => `Course book 1, page ${n}`,
  B2: n => `Course book 2, page ${52 + n}`,
  B3: n => `Course book 3, page ${104 + n}`,
  CL: n => `Portfolio checklist, page ${n}`
};
const Q = (t, q, o, a, why, src, img, alt) => ({ t, q, o, a, why, src, img, alt });

window.QUESTIONS = [

/* ---------- Image questions ---------- */
Q('Glazing','An independent glass panel has been fitted in front of an existing single glazed window, as in the photo. How is this glazing recorded?',
 ['Secondary glazing','Double glazing','Triple glazing','Single glazing with draught proofing'],0,
 'When an independent glass panel is installed in front of an existing single glazed window, it is secondary glazing.',SRC.B1(12),'img/secondary-glazing.jpg','Two windows showing a second pane fitted inside an existing window'),
Q('Glazing','The cross-section of this window frame shows the glass build-up. What type of glazing is it?',
 ['Triple glazing: three layers of glass with two air gaps','Double glazing: two layers of glass with one air gap','Secondary glazing: an extra panel fitted in front','Single glazing: one layer of glass'],0,
 'Triple glazing has three layers of glass panel with two air gaps in between.',SRC.B1(11),'img/triple-glazing.jpg','Cross-section of a PVC window frame with three panes of glass'),
Q('Dwelling forms','How many party walls and heat loss walls does this semi-detached house have?',
 ['1 party wall and 3 heat loss walls','2 party walls and 2 heat loss walls','0 party walls and 4 heat loss walls','1 party wall and 2 heat loss walls'],0,
 'A semi-detached property is joined to one other, so it has 1 party wall and 3 heat loss (HLP) walls.',SRC.B1(20),'img/semi-detached.jpg','Pair of semi-detached brick houses with garages'),
Q('Dwelling forms','This aerial view shows detached houses. How many party walls does a detached property have?',
 ['0','1','2','4'],0,
 'A detached property stands alone, so it has heat loss walls on all sides and no party walls.',SRC.B1(19),'img/detached-aerial.jpg','Aerial photo of detached houses with red tiled roofs'),
Q('Dwelling forms','How many party walls and heat loss walls does this mid-terraced house have?',
 ['2 party walls and 2 heat loss walls','1 party wall and 3 heat loss walls','2 party walls and 3 heat loss walls','0 party walls and 4 heat loss walls'],0,
 'A mid-terrace sits in a row, sharing common walls on both sides: 2 party walls and 2 heat loss walls.',SRC.B1(21),'img/mid-terrace.jpg','Terraced house in a row with bay windows'),
Q('Dimensions','Using the canted bay diagram, the bay is 3.2 m wide (the long edge) and 0.6 m deep. What is its estimated floor area?',
 ['1.44 m²','1.92 m²','2.40 m²','0.72 m²'],0,
 'Floor area of a canted bay is depth × three quarters of the width: 0.6 × (3.2 × 0.75) = 0.6 × 2.4 = 1.44 m².',SRC.B1(36),'img/canted-bay.jpg','Diagram of a canted bay window plan with a depth arrow'),
Q('Dimensions','In this plan of a semi-detached property, which expression gives the heat loss perimeter (HLP)?',
 ['a + b + c','a + b + c + d','b + c + d','a + c'],0,
 'HLP is the total length of all heat loss walls, excluding party walls. Wall d is the party wall, so HLP = a + b + c.',SRC.B1(31),'img/hlp-semi-plan.jpg','Plan of a house with sides labelled a, b, c and d'),
Q('Dimensions','The main part of this plan is 4 m × 4.2 m and the bay is 3.6 m wide and 0.9 m deep. What is the total floor area?',
 ['19.23 m²','20.04 m²','16.80 m²','17.37 m²'],0,
 'Main area 4 × 4.2 = 16.8 m². Bay = (3.6 × 0.75) × 0.9 = 2.43 m². Total = 19.23 m².',SRC.B2(37),'img/bay-plan.jpg','Plan of a rectangular room with a small bay at the front'),
Q('Walls','This solid stone wall (sandstone or limestone) is typical of Yorkshire, Hampshire and Devon. What thickness range would you expect?',
 ['400 mm to 600 mm','100 mm to 150 mm','230 mm to 250 mm','270 mm to 300 mm'],0,
 'Sandstone and limestone walls are typically 400 to 600 mm thick.',SRC.B1(48),'img/stone-sandstone.jpg','Stone wall building with a slate roof by the coast'),
Q('Walls','This granite stone barn is typical of rural areas. How does the course describe the U-value of most solid stone properties built pre-1900?',
 ['Very poor','Excellent','Average','Always better than cavity walls'],0,
 'Most solid stone properties were built pre-1900 or early 1900s and have a very poor U-value. Thickness can vary.',SRC.B1(49),'img/stone-granite.jpg','Granite stone barn with a pitched roof'),
Q('Walls','The outer leaf of a cavity wall is usually built in which bond, shown here?',
 ['Stretcher bond','Headers only','Stretchers and headers alternating (solid brick)','Random rubble'],0,
 'Cavity walls usually have a stretcher bond outer leaf. Solid brick walls use a mix of stretchers and headers.',SRC.B2(3),'img/stretcher-bond.jpg','Close-up of red brickwork laid in stretcher bond'),
Q('Walls','Drilled holes in the brick joints, as shown, suggest what?',
 ['Retro-filled cavity wall insulation','Solid wall with internal insulation','A timber frame construction','Dry lining on battens'],0,
 'Drilled hole marks suggest retro-filled cavity wall insulation. Without visual or documentary evidence, choose "As built". An insulation certificate is also acceptable evidence.',SRC.B2(4),'img/drill-holes.jpg','Brickwork with small drilled holes visible in the mortar'),
Q('Walls','Timber visible on the outside of a pre-1900 property, as here, indicates which wall construction?',
 ['Historic timber frame','Modern timber frame','System build','Cob'],0,
 'Historic timber frame construction is normally visible from outside as timber. Buildings are usually pre-1900 or early 1900s.',SRC.B2(6),'img/timber-frame-historic.jpg','Large house with exposed timber framing on the walls'),
Q('Walls','Components made off site and assembled on site, such as this steel frame, describe which construction?',
 ['System built','Cavity wall','Cob','Solid brick'],0,
 'System built construction uses components made off site, such as steel frames, prefabricated modules or concrete panels.',SRC.B2(8),'img/steel-frame.jpg','Steel frame structure of a building under construction'),
Q('Walls','This block is built from concrete panels. Which wall type does it fall under in RDSAP?',
 ['System built','Timber frame','Cavity wall','Stone'],0,
 'Blocks and concrete panels of various sizes are system built.',SRC.B2(9),'img/concrete-panel-block.jpg','Block of flats built from concrete panels'),
Q('Walls','This high-rise block was built in 1972 and has a cavity/stretcher bond exterior wall. How should the wall be entered?',
 ['Cavity wall','System built','Solid brick','Timber frame'],0,
 'High-rise properties (more than 4 storeys) built non-traditionally are system built, but if built during or after 1967 with a cavity/stretcher bond exterior wall, enter it as a cavity wall.',SRC.B2(10),'img/high-rise.jpg','Tall residential tower block'),
Q('Walls','This wall is made from mud, clay or chalk and straw. What is it called, and how thick is it typically?',
 ['Cob, 450 to 600 mm','Solid brick, 230 to 250 mm','Timber frame, 270 mm onwards','System build, 100 to 150 mm'],0,
 'Cob walls are mud/clay/chalk and straw construction, typically 450 to 600 mm thick.',SRC.B2(11),'img/cob-house.jpg','Thatched cob house with rounded walls'),
Q('Walls','For the purpose of RDSAP, this home is a prefabricated dwelling of lightweight modular construction without its own foundations. What is it?',
 ['A park home','A detached bungalow','A mobile conservatory','A maisonette'],0,
 'A park home is a prefabricated, modular, lightweight dwelling without its own foundations. It may sit on a concrete base and be capable of being moved.',SRC.B2(12),'img/park-home.jpg','White static caravan park home with decking'),
Q('Walls','You are assessing a flat. The wall shown faces an unheated corridor. How is it recorded?',
 ['As a heat loss wall and a sheltered alternative wall','As a party wall','As an external wall with no alternative wall','It is ignored'],0,
 'A wall facing an unheated corridor is a heat loss wall and is recorded separately as a sheltered alternative wall. A wall facing a heated corridor is recorded as a party wall.',SRC.B2(14),'img/unheated-corridor.jpg','Interior of an unheated flat corridor with doors'),
Q('Walls','Where is the primary place to identify the construction of a party wall?',
 ['In the loft space, by viewing the gable end wall','From the front of the property','From the garden side','From the electricity meter cupboard'],0,
 'Party wall type is identified from the loft space. If it cannot be identified or there is no access, record "unable to determine". Stay safe: head and shoulders from the loft hatch only.',SRC.B2(16),'img/loft-party-wall.jpg','View inside a loft space showing a brick wall and timbers'),
Q('Roofs','The structure shown is part of a pitched roof. Which timbers run up the slope of the roof from the ridge down to the walls?',
 ['Rafters','Joists','Purlins only','Lintels'],0,
 'Rafters run along the slope of a pitched roof. Joists run horizontally and typically form the ceiling below the loft.',SRC.B2(18),'img/rafters.jpg','Loft roof structure showing timber rafters'),
Q('Roofs','What should you do when you see loft insulation like this?',
 ['Measure the thickness and take a photo as evidence','Enter "unknown" insulation','Assume 100 mm','Record as "as built"'],0,
 'Measure the insulation thickness and take photographic evidence. Unknown insulation should be avoided unless there is no access.',SRC.B2(19),'img/loft-measure.jpg','Tape measure in mineral wool loft insulation'),
Q('Roofs','Which RDSAP roof type applies to this property?',
 ['PT Pitched (thatch)','PA Pitched (slates/tiles), access to loft','PS Pitched, sloping ceiling','F Flat'],0,
 'Thatch has its own roof type, PT Pitched (thatch). Measure insulation thickness and take a photo, or avoid "unknown" unless there is no access to the loft.',SRC.B2(21),'img/thatch.jpg','White cottage with a thatched roof'),
Q('Roofs','How should insulation on this flat roof be recorded when there is no evidence?',
 ['As built','Unknown','Retro-fitted, 100 mm','No insulation'],0,
 'Flat roof insulation is normally input as "as built". Documentary evidence is required to record flat roof insulation thickness.',SRC.B2(23),'img/flat-roof.jpg','Flat roof with a black membrane covering'),
Q('Roofs','The multi-foil insulation here measures 100 mm. What thickness do you enter?',
 ['200 mm','100 mm','50 mm','150 mm'],0,
 'Multi-foil and rigid board insulation thickness is doubled when entered, so 100 mm is entered as 200 mm.',SRC.B2(24),'img/multi-foil.jpg','Foil insulation between roof rafters'),
Q('Roofs','A room in the roof is classed as such, rather than a separate storey, when the common wall height is below what?',
 ['1.8 m for at least 50% of the common wall','1.5 m for at least 25% of the common wall','2.1 m for all of the common wall','1.8 m for 100% of the common wall'],0,
 'The common wall must be less than 1.8 m high for at least 50% of its length (excluding gable ends and party walls) for it to be a room in roof.',SRC.B2(26),'img/roof-room.jpg','Loft bedroom with sloping ceilings and roof windows'),
Q('Floors','An air brick like this on the outside wall points to which type of floor?',
 ['Suspended timber (or suspended concrete)','Solid','Floor above an unheated space','Floor to external air'],0,
 'Suspended floors normally have an air brick and feel hollow in a stamp test. Solid floors have no air brick.',SRC.B2(32),'img/airbrick.jpg','Red air brick set in a brick wall at ground level'),
Q('Age bands','Solid walls of 220 to 240 mm, sash windows, no front garden and the property right on the road. Which age band fits best?',
 ['1850 to 1900s','1930s to 1949','1970s','1990s'],0,
 'The 1850 to 1900s band has solid walls (220 to 240 mm), sash windows, no front garden and properties by the road.',SRC.B2(40),'img/age-victorian.jpg','Stone terraced houses directly on the street'),
Q('Age bands','Full bay windows, a front garden, half-hip pitched roofs and cavity walls over 240 mm. Which age band fits best?',
 ['1930s to 1949','1850 to 1900s','1980s','1990s'],0,
 'The 1930s to 1949 band features full bay windows, front gardens and half-hip roofs. About 40% of UK houses fit this band.',SRC.B2(42),'img/age-1930s.jpg','Semi-detached 1930s house with a bay window'),
Q('Age bands','Cavity walls of 270 mm or more and often no chimney. What does the course say is the reason many homes from this period have no chimney?',
 ['The coal miners\' strikes','Planning rules banned chimneys','Central heating was compulsory','Roofs were too low'],0,
 'In the 1970s chimneys were often left out because of the coal miners\' strikes. Timber frame houses were also built.',SRC.B2(44),'img/age-1970s.jpg','Brick terraced houses with no chimneys'),
Q('Age bands','Smaller gardens, smaller windows and the arrival of mass-produced double glazing. Which age band fits best?',
 ['1980s','1950 to 1966','1900 to 1929','1850 to 1900s'],0,
 '1980s houses had cavity walls of 280 mm or more, smaller gardens, smaller windows and mass-produced double glazing units.',SRC.B2(45),'img/age-1980s.jpg','Detached brick house with an integral garage'),
Q('Age bands','Trickle vents over the windows, external extractor fans and large three-storey houses. Which age band fits best?',
 ['1990s','1970s','1930s to 1949','1900 to 1929'],0,
 '1990s houses have 290 to 300 mm cavity walls, trickle vents, external extractor fans and up to 3 storeys.',SRC.B2(46),'img/age-1990s.jpg','Three-storey brick house'),
Q('Heating','The white plastic pipe from the boiler to a foul drain (shown) is a sign of which type of boiler?',
 ['A condensing boiler','An open flue back boiler','A range cooker','A warm air unit'],0,
 'A plastic condensate drain-pipe (200 to 250 mm) from the boiler to a foul drain is one sign of a condensing boiler. Other signs: a fanned flue with a plastic terminal and a vapour plume.',SRC.B3(4),'img/condensate-pipe.jpg','Illustration of a plastic pipe from a wall to a drain'),
Q('Heating','A traditional cast-iron cooker with burners that also heats water for radiators. What is it?',
 ['A range cooker boiler','A combination boiler','A CPSU','A warm air system'],0,
 'Range cooker boilers (gas and oil) are traditional cast-iron cooking appliances designed to provide heat to the space and normally domestic hot water.',SRC.B3(7),'img/range-cooker.jpg','Dark blue range cooker in a kitchen'),
Q('Heating','A bulk tank like this is used for LPG. When can LPG be entered under condition 18 at mains gas prices?',
 ['Only when documentary evidence confirms mains gas prices','Always, when the tank is fixed','Never','When the tank is more than 1,000 litres'],0,
 'Condition 18 applies only if documentary evidence confirms the property receives LPG at mains gas prices. Treat LNG as mains gas.',SRC.B3(9),'img/lpg-tank.jpg','Large white bulk propane storage tank'),
Q('Heating','This old floor-standing boiler draws combustion air from the room and the gases rise up a flue. Which flue type is this, and what should be in the same room?',
 ['Open flue; an air brick','Balanced flue; a trickle vent','Fan flue; a cooker hood','Open flue; an extractor fan'],0,
 'Open flues are traditional on older floor-standing gas, solid fuel and oil boilers. An air brick should be present in the same room as the boiler.',SRC.B3(10),'img/open-flue-boiler.jpg','Floor-standing white boiler in a kitchen'),
Q('Heating','A square metal mesh terminal about 30 cm × 30 cm on an external wall is typical of which flue?',
 ['Balanced (room sealed) flue','Open flue','Flueless','Warm air duct'],0,
 'A balanced flue has a square metal mesh terminal, approximately 30 cm × 30 cm, with the boiler on the inside of an external wall.',SRC.B3(11),'img/balanced-flue.jpg','Square metal mesh flue terminal on a brick wall'),
Q('Heating','A round, mostly plastic pipe terminal through the wall indicates which flue type?',
 ['Fan flue','Open flue','Balanced flue with a square terminal','Chimney flue'],0,
 'A fan flue is a form of balanced flue with a fan for extraction. It can be identified by a round, mostly plastic pipe.',SRC.B3(32),'img/fan-flue.jpg','Round plastic flue terminal in a brick wall'),
Q('Heating','Deep (over 200 mm), brown or beige, typically installed in the 1960s. What is this appliance?',
 ['An old storage heater','A modern slimline storage heater','A high heat retention heater','An electric panel heater'],0,
 'Old storage heaters are quite deep (over 200 mm) and often brown or beige. They were typically installed in the 1960s.',SRC.B3(12),'img/old-storage-heater.jpg','Brown old-style electric storage heater'),
Q('Heating','This slimline heater has air grilles at the top and a fan. Which type is it most likely?',
 ['Fan assisted storage heater','Direct acting panel heater','Warm air unit','Electric boiler'],0,
 'Fan assisted storage heaters are slimmer, can be identified by their controls and by air grilles at the top and bottom, and have two power cables: one for storage and one for the fan.',SRC.B3(13),'img/slimline-storage.jpg','White slimline electric storage heater'),
Q('Heating','If a high heat retention (HHR) storage heater is not found in the PCDF, how should it be entered?',
 ['As fan assisted','As a direct acting heater','As an old storage heater','As an electric boiler'],0,
 'If the HHR storage heater is not present in the PCDF, enter it as fan assisted. HHR heaters can only be selected from the PCDF for the code SEK.',SRC.B3(14),'img/hhr-storage.jpg','White high heat retention storage heater'),
Q('Heating','This outdoor unit takes ambient heat from the air to heat the home. What is it?',
 ['An air source heat pump','A ground source heat pump','A warm air system','A micro CHP unit'],0,
 'Air source heat pumps take ambient heat from the air. Ground source pumps use underground collectors; water source pumps use water.',SRC.B3(21),'img/ashp.jpg','Outdoor air source heat pump unit beside a wall'),
Q('Heating','A floor-standing unit 1.5 to 2 metres tall that blows heated air through ducts and low-level wall vents. Which system is it?',
 ['Warm air system','CPSU','Electric direct acting boiler','Community heating'],0,
 'Warm air systems can run on gas, oil or electricity. The main unit is floor-mounted, about 1.5 to 2 m tall, and the low-level vents are a useful indicator.',SRC.B3(23),'img/warm-air-unit.jpg','Tall floor-standing warm air heating unit'),
Q('Heating','Electric underfloor heating mats like this are treated the same as which heater type?',
 ['Electric panel convector heaters','Electric storage heaters','Electric boilers','Warm air systems'],0,
 'Underfloor heating mats are the same as electric panel convector heaters.',SRC.B3(30),'img/ufh-mat.jpg','Red electric underfloor heating mat unrolled'),
Q('Ventilation','A flueless gas fire like this must be entered in the ventilation section. What does it require in the same room for safety?',
 ['An air brick','A chimney','A passive stack vent','A mechanical extract fan'],0,
 'Flueless gas fires require an air brick in the same room. Record the number of flueless gas fires, and also enter the fire in the relevant heating section.',SRC.B3(38),'img/flueless-fire.jpg','Wall-mounted flueless gas fire with orange flames'),
Q('Hot water','This cylinder is heated indirectly by the boiler. What hot water type do you choose?',
 ['From primary heating','Electric immersion','Instantaneous point of use','Community heating'],0,
 'If hot water is provided by a boiler (with or without a cylinder), choose "from primary heating". Any immersion heater should be ignored and the code HWP used.',SRC.B3(44),'img/indirect-cylinder.jpg','Green hot water cylinder with pipework'),
Q('Hot water','You cannot measure the insulation on this jacket-insulated cylinder. What default thickness applies?',
 ['12 mm for a jacket (25 mm for foam)','25 mm for a jacket (12 mm for foam)','50 mm for either','0 mm'],0,
 'If you cannot measure the cylinder insulation, the default is 25 mm for foam and 12 mm for a jacket.',SRC.B3(45),'img/cylinder-jacket.jpg','Hot water cylinder wrapped in a quilted jacket'),
Q('Hot water','This unvented cylinder has no visible insulation. What should be assumed?',
 ['50 mm of spray foam insulation and a cylinder thermostat','No insulation','12 mm loose jacket','25 mm foam and no thermostat'],0,
 'For unvented cylinders where the insulation is not visible, 50 mm of spray foam should be assumed, and a cylinder thermostat assumed.',SRC.B3(46),'img/unvented-cylinder.jpg','White unvented hot water cylinder'),
Q('Hot water','An electric unit over the sink, as shown (or an electric shower as the only hot water source). How is it entered?',
 ['Instantaneous point of use (electric)','Electric immersion','From primary heating','Single point gas water heater'],0,
 'Over-sink or under-sink electric units, and electric showers if they are the only hot water system, are entered as instantaneous point of use.',SRC.B3(47),'img/electric-point-of-use.jpg','White electric water heater above a basin'),
Q('Hot water','A wall-mounted gas water heater with three pipes (cold, hot and gas supply). What is it?',
 ['Single or multi point water heater','CPSU','Combination boiler','Range cooker'],0,
 'Single or multi point gas water heaters provide hot water to one or more outlets and normally have 3 pipes: cold, hot, and the gas supply.',SRC.B3(47),'img/gas-multipoint.jpg','Wall-mounted gas multipoint water heater'),

/* ---------- Text questions: general and the assessment ---------- */
Q('RDSAP basics','On construction (SAP) assessments are for new builds from which year?',['2008 onwards','1990 onwards','1967 onwards','2020 onwards'],0,'On Construction Assessments (SAP) are for new builds built from 2008 onwards.',SRC.B1(3)),
Q('RDSAP basics','When can an RDSAP be carried out on a new build?',['Only if its SAP has expired','Never','Whenever the owner asks','Only if it has more than 3 bedrooms'],0,'An RDSAP can only be carried out on a new build if it has a SAP that has expired.',SRC.B1(3)),
Q('RDSAP basics','A property is sold to a family member. Which transaction type applies?',['Non marketing sale','Marketing sale','ECO assessment','Marketing rental'],0,'Non marketing sales cover right to buy or sale to a family member. A marketing sale is a residential property sold on the open market.',SRC.B1(5)),
Q('RDSAP basics','If "None of the above" is chosen as the transaction type, what must you do?',['Include the reason in the site notes','Leave it blank','Call the accreditation scheme','Choose marketing sale instead'],0,'The reason must be included in the site notes.',SRC.B1(5)),
Q('RDSAP basics','What does the terrain type determine?',['The average wind speed at the property','The heating system efficiency','The age band','The wall U-value'],0,'Terrain type (urban, suburban or rural) determines the average wind speed at the property.',SRC.B1(6)),
Q('RDSAP basics','How many properties are needed in the portfolio to become DEA qualified?',['5','3','10','1'],0,'The course requires a portfolio of 5 properties to become DEA qualified.',SRC.B1(2)),
Q('RDSAP basics','Which of these is NOT listed as a way to prove windows were installed after 2002?',['The colour of the frame','A thermal space bar','A kite mark on PVC frame windows','A FENSA certificate'],0,'Acceptable proof: thermal space bar, kite mark on PVC frame windows, or a FENSA certificate. Frame colour is not proof.',SRC.B1(13)),

/* ---------- Windows and doors ---------- */
Q('Glazing','Which window installation age options are available in RDSAP 10?',['Pre 2002, Post 2002, Post 2022, Unknown date','Pre 1990, Post 1990, Post 2010','Pre 2000, Post 2000, Post 2020','Pre 2002 and Post 2002 only'],0,'Options are Pre 2002, Post 2002, Post 2022 and Unknown date.',SRC.B1(13)),
Q('Glazing','What should you select for window installation age if there is no evidence of the date?',['Unknown date','Pre 2002','Post 2002','Post 2022'],0,'Choose unknown if there is no evidence or documentary evidence of the date.',SRC.B1(13)),
Q('Glazing','How is the percentage of multiple glazed windows calculated?',['Multi glazed windows ÷ total windows × 100','Total windows ÷ multi glazed windows × 100','Glazed area ÷ floor area × 100','Single glazed ÷ multi glazed × 100'],0,'Count all windows and use: total multi glazed windows / total windows × 100.',SRC.B1(14)),
Q('Glazing','PVC frame double glazing, pre 2002 or unknown date. Which glazing gap options do you choose from?',['6 mm, 12 mm, or 16 mm or more','4 mm, 8 mm, or 12 mm','3 mm, 6 mm, or 9 mm','10 mm, 20 mm, or 30 mm'],0,'Select the nearest of 6 mm, 12 mm or 16 mm or more.',SRC.B1(15)),
Q('Glazing','Which windows are included when assessing window area?',['All windows and glazed doors of the dwelling including extensions, but not conservatories','Main house windows only','All windows including conservatories','Windows only, without glazed doors'],0,'Consider the whole dwelling (windows and glazed doors) including extensions, not conservatories.',SRC.B1(7)),
Q('Glazing','How are double, triple and secondary glazed windows treated for draught proofing?',['Considered 100% draught proofed','Considered 50% draught proofed','Must be tested individually','Not considered'],0,'Double, triple and secondary glazed windows and doors are considered 100% draught proofed.',SRC.B1(18)),
Q('Doors','An external door has at least 60% glazing. How is it classed?',['As a window','As a door','As a double door','It is ignored'],0,'An external door with at least 60% glazing is a window and is not included in the door count.',SRC.B1(16)),
Q('Doors','A double door at the rear of a property is recorded as…',['2 doors','1 door','1 window','A conservatory door'],0,'A double door should be recorded as 2 doors.',SRC.B1(16)),
Q('Doors','Is a door to a heated access corridor included in the external door count?',['No','Yes','Only if glazed','Only if it is a fire door'],0,'A door to a heated access corridor is not included.',SRC.B1(16)),
Q('Doors','There is no U-value evidence for the external doors. How many insulated doors do you record?',['0','1','All of them','Half of them'],0,'A door is counted as insulated only with documentary evidence. Record zero insulated doors if no U-value evidence is available.',SRC.B1(17)),
Q('Doors','Two insulated doors have different U-values (documentary evidence). What U-value do you enter?',['The average U-value','The lowest U-value','The highest U-value','The newest door\'s U-value'],0,'If there is more than one insulated door with different U-values, enter the average U-value.',SRC.B1(17)),

/* ---------- Dwelling forms ---------- */
Q('Dwelling forms','A double row of houses sharing a common back wall (typical in northern industrial cities) is known as…',['Enclosed end/mid terrace (back to back)','Detached','Semi-detached','Maisonette'],0,'Enclosed end/mid terrace houses are back to back houses sharing a common rear wall.',SRC.B1(22)),
Q('Dwelling forms','Which features will a house always have, but a flat may not?',['A ground floor, its own entrance and its own roof','Two storeys, a garden and a garage','A chimney, a loft and a garage','Its own entrance, a garden and a drive'],0,'A house will always have a ground floor, its own entrance and its own roof; a flat may not.',SRC.B1(23)),
Q('Dwelling forms','A bungalow with a room in the roof is treated as…',['A house','A flat','A maisonette','A park home'],0,'A ground floor, single storey house is a bungalow, and a bungalow with a room in roof should be treated as a house.',SRC.B1(23)),
Q('Dwelling forms','What is a maisonette?',['A flat with more than one floor, or a purpose-built flat with its own entrance','A one-bedroom studio','A detached bungalow','A flat above a shop only'],0,'A maisonette is a flat with more than one floor, or a purpose-built flat with its own entrance.',SRC.B1(23)),
Q('Dwelling forms','Which room is NOT counted as a habitable room?',['Utility room','Bedroom','Dining room','Living room'],0,'The count excludes the hall, stairs, landing, kitchen, utility room, bathroom, cloakroom and en suite.',SRC.B1(24)),
Q('Dwelling forms','What must a kitchen have to be counted as a kitchen/diner?',['Space for a table and 4 chairs','A breakfast bar','A window onto the garden','At least 20 m² of floor area'],0,'For a kitchen to be a kitchen/diner it must have space for a table and 4 chairs.',SRC.B1(24)),
Q('Dwelling forms','A lounge and dining room are separated by a door that has been temporarily removed. How many habitable rooms is that?',['2','1','3','0'],0,'A lounge/dining room where the door is temporarily removed still counts as 2 habitable rooms.',SRC.B1(24)),

/* ---------- Dimensions ---------- */
Q('Dimensions','Which wall is NOT included in the heat loss perimeter?',['A party wall','A wall next to an unheated garage','A wall next to an unheated conservatory','An external wall'],0,'HLP includes all exposed walls and walls touching unheated spaces, but not party walls.',SRC.B1(29)),
Q('Dimensions','What is assumed for heat loss through party walls?',['Zero','50% of an external wall','The same as an external wall','Half the floor U-value'],0,'Losses or gains through party walls to other dwellings are assumed to be zero.',SRC.B1(25)),
Q('Dimensions','A semi-detached house has external walls of 5.2 m, 7.1 m and 5.2 m, and a 7.1 m party wall. What is the heat loss perimeter?',['17.5 m','24.6 m','12.3 m','14.2 m'],0,'HLP excludes the party wall: 5.2 + 7.1 + 5.2 = 17.5 m.',SRC.B1(31)),
Q('Dimensions','To what accuracy should measurements be recorded?',['2 decimal places','Whole metres','1 decimal place','3 decimal places'],0,'Measurement accuracy should be up to 2 decimal places, with 5% tolerance acceptable in overall measurements.',SRC.B1(26)),
Q('Dimensions','What overall measurement tolerance is acceptable?',['5%','1%','10%','15%'],0,'There is a 5% tolerance acceptable in overall measurements.',SRC.B1(26)),
Q('Dimensions','Gross internal area is measured to which point?',['The internal face of the perimeter walls at each floor level','The external face of the walls','The centre of the walls','The outer edge of the foundations'],0,'Gross internal area is the area measured to the internal face of the perimeter walls at each floor level.',SRC.B1(26)),
Q('Dimensions','How is the floor area of a staircase measured?',['As if there were no stairs but a floor in their place at each level','It is excluded','Measured at 50% of its area','Only at the lowest level'],0,'Stairs should be measured as if there were no stairs but a floor in their place at each level.',SRC.B1(27)),
Q('Dimensions','If a basement or room in the roof is included, how should the whole property be measured?',['Internally','Externally','By estimate','From the floor plans only'],0,'If a basement or room in roof is included, the whole property should be measured internally.',SRC.B1(27)),
Q('Dimensions','How are lowered ceilings treated when measuring storey height?',['They are disregarded','They are measured at their lowest point','They are averaged','They are treated as a mezzanine'],0,'Storey height is measured between ceiling surfaces; lowered ceilings are disregarded.',SRC.B1(34)),
Q('Dimensions','How do you enter the part of a property above and below a mezzanine deck?',['As a two storey extension, with the rest as a single level at full height','As a single storey','As a basement','It is ignored'],0,'Enter the part above and below the mezzanine deck as a two storey extension and treat the remainder as a single level with full floor to ceiling/roof height.',SRC.B1(37)),
Q('Dimensions','Extension data in RDSAP is…',['Entered separately from the main house','Combined with the main house','Optional','Averaged with the main house'],0,'Extension data is recorded separately, because its age band and software defaults can differ. Up to 4 extensions can be recorded.',SRC.B2(38)),
Q('Dimensions','What is the maximum number of extensions that can be recorded?',['4','2','1','6'],0,'You can record up to 4 extensions.',SRC.B2(38)),

/* ---------- Conservatories, porches, other spaces ---------- */
Q('Dwelling parts','What defines a conservatory in RDSAP?',['75% translucent roof and 50% translucent walls','50% translucent roof and 75% translucent walls','Any glazed extension','Any extension with a patio door'],0,'A conservatory has a 75% translucent roof and 50% translucent walls. Otherwise, treat it as an extension.',SRC.B1(38)),
Q('Dwelling parts','A conservatory is separated by an external quality door. What data is required for it?',['None','Full dimensions','Wall and roof type only','Window area only'],0,'No data is required for a separated conservatory. Patio and original French doors count as external quality doors.',SRC.B1(38)),
Q('Dwelling parts','When is a porch included in the assessment?',['If it is heated or open plan with the main house','Always','Never','Only if it has a door'],0,'Include a porch if it is heated or open plan (no wall in between). Disregard if unheated.',SRC.B1(39)),
Q('Dwelling parts','What is the minimum floor area for a draught lobby to qualify?',['2 m²','1 m²','4 m²','0.5 m²'],0,'A draught lobby must be an arrangement of two doors forming an airlock at the front entrance, of at least 2 m². Rear lobbies are not included.',SRC.B1(40)),
Q('Dwelling parts','When should a basement be included?',['If heated and accessed by a permanent fixed staircase, or open to the main house','Always','Never','Only if it has windows'],0,'Include only if heated and accessed via a permanent fixed staircase so one can walk down facing forwards, or if it opens to the main house with no door or wall.',SRC.B1(41)),
Q('Dwelling parts','A garage has its own electric heater. Is it included?',['No, only if heated from the main heating system','Yes','Yes, if more than 15 m²','Yes, if attached'],0,'Include a garage only if heated from the main building\'s heating system. Disregard it even with an individual heater.',SRC.B1(42)),

/* ---------- Walls ---------- */
Q('Walls','What is the typical thickness of solid brick walls?',['230 mm to 250 mm','100 mm to 150 mm','400 mm to 600 mm','290 mm to 300 mm'],0,'Solid brick is usually 230 to 250 mm; Victorian or older solid walls can be 300 to 500 mm.',SRC.B1(50)),
Q('Walls','What evidence is needed to record external or internal wall insulation on a solid wall?',['Photographic or documentary evidence of insulation and thickness','The householder\'s verbal confirmation','None','Only a tap test'],0,'You must have photographic or documentary evidence of the insulation and its thickness.',SRC.B1(51)),
Q('Walls','A solid wall has both internal and external insulation. How do you enter it?',['Add the thicknesses together and enter as external insulation','Enter internal only','Enter external only','Enter the larger of the two as internal'],0,'If there is both, add the insulation thicknesses together and enter as external insulation.',SRC.B1(51)),
Q('Walls','There is no evidence of wall insulation. What do you choose?',['As built','Unknown','Internal','External'],0,'When no evidence is available choose "As built". Avoid "Unknown" or you will be audited.',SRC.B1(52)),
Q('Walls','Which wall insulation option should be avoided because you will be audited?',['Unknown','As built','Internal','External'],0,'Avoid using "Unknown" wall insulation.',SRC.B1(52)),
Q('Walls','What does a hollow sound from a tap test suggest about a wall?',['It is dry lined','It is solid stone','It has external insulation','It has cavity insulation'],0,'A hollow sound is expected if the wall is dry lined. If you are not sure, record no dry lining.',SRC.B2(1)),
Q('Walls','The same construction has different thicknesses at the front and back. What do you record?',['The average thickness','The thinnest wall','The thickest wall','The front wall thickness'],0,'Record an average wall thickness if the same construction has variable thicknesses. Photos must be taken.',SRC.B2(2)),
Q('Walls','Which is an indicator of a modern timber frame wall?',['Windows appear in-set rather than on the outer skin','Walls of about 150 mm thickness','Drilled holes in the mortar','Stone quoins at the corners'],0,'In modern timber frame, window frames sit inside the timber frame so appear in-set. Also check for vertical timber panels in the loft and hollow sounds when tapping.',SRC.B2(7)),
Q('Walls','An alternative wall of different construction is disregarded when it is less than what share of the exposed wall area?',['10%','5%','25%','50%'],0,'Disregard an alternative wall of a different construction if it is less than 10% of the total exposed wall area of the building part. A sheltered wall is always included.',SRC.B2(14)),
Q('Walls','What is the maximum number of alternative walls in RDSAP?',['5','2','10','1'],0,'There can be up to 5 alternative walls: one for the main building and one for each extension.',SRC.B2(15)),
Q('Walls','What construction is assumed for a sheltered wall?',['The same as the main wall','Solid brick','Cavity wall','System built'],0,'Sheltered wall construction is assumed to be the same as the main wall, regardless of type.',SRC.B2(15)),
Q('Walls','For party wall type, what do you record if it cannot be identified or there is no loft access?',['Unable to determine','Solid','Cavity','Timber frame'],0,'When identification is not possible or there is no access, record "unable to determine".',SRC.B2(16)),
Q('Walls','Is an EPC required by regulation for a park home?',['No, though it may be needed for funding such as ECO','Yes, always','Yes, if sold','Yes, if let'],0,'The energy performance of buildings regulations do not require an EPC for a park home, but it may be needed for funding purposes such as ECO.',SRC.B2(13)),

/* ---------- Roofs ---------- */
Q('Roofs','Loft insulation is glass fibre or mineral wool measuring 150 mm. What do you enter?',['150 mm','300 mm','75 mm','Unknown'],0,'Enter the same as what you measure in mm for glass fibre or mineral wool.',SRC.B2(24)),
Q('Roofs','Rigid board insulation measures 100 mm. What thickness do you enter?',['200 mm','100 mm','50 mm','300 mm'],0,'Rigid board insulation thickness is doubled when entered, so 100 mm is entered as 200 mm.',SRC.B2(24)),
Q('Roofs','There is no loft hatch or other means of access. How is "no access" recorded?',['No access','Access, loft insulation unknown','As built','Zero insulation'],0,'"No access" means there is no loft hatch or other means of gaining access to the loft.',SRC.B2(25)),
Q('Roofs','A loft hatch exists but cannot be used on the day (painted over or blocked). What do you record?',['Access, loft insulation unknown','No access','As built','No insulation'],0,'If there is a hatch but it cannot be used on the visit, record "access, loft insulation unknown".',SRC.B2(25)),
Q('Roofs','Both joist and rafter insulation are present. What do you record?',['Joist insulation only','Rafter insulation only','Both added together','The thicker of the two as rafters'],0,'If both joist and rafter insulation are present, record joist insulation only.',SRC.B2(25)),
Q('Roofs','A loft is fully boarded and the householder has no documentary evidence. What do you enter, unless the boards are lifted?',['Unknown','150 mm','As built','No insulation'],0,'If the loft is fully boarded enter unknown unless the householder has documentary evidence or is prepared to lift the boards.',SRC.B2(25)),
Q('Roofs','RDSAP does not recommend more loft insulation if there is at least how much?',['150 mm','100 mm','50 mm','300 mm'],0,'RDSAP does not recommend more insulation if there is at least 150 mm.',SRC.B2(25)),
Q('Roofs','A pitched roof has a sloping ceiling and no evidence of insulation. What do you record?',['As built','Unknown','100 mm','No insulation'],0,'Record "As built" insulation unless visual or documentary evidence is available. Avoid "unknown".',SRC.B2(20)),
Q('Roofs','What is a Type 1 room in roof in RDSAP 10?',['A room fully contained within the roof space, with no common wall','A room with continuous common walls','A separate storey','A loft with no windows'],0,'Type 1 is a room fully contained within the roof space with no shared (common) wall. Type 2 includes continuous common walls.',SRC.B2(27)),
Q('Roofs','The common wall of a room in roof is…',['The vertical continuation of the external wall of the storey below, excluding gable ends and party walls','Any gable wall','The party wall','A wall in the loft'],0,'It is a vertical extension of the external wall from the storey below and does not include gable end walls or party walls.',SRC.B2(27)),
Q('Roofs','When are detailed measurements of a room in roof required?',['Only if slope, stud wall or gable have different insulation levels with known U-values','Always','Never','Only for Type 2'],0,'Detailed measurements are required only if evidence shows different insulation levels and each U-value is known.',SRC.B2(30)),
Q('Roofs','A flat has another dwelling above. What roof data is required?',['No further data','Insulation thickness','Roof U-value','Photograph of the roof'],0,'For "another dwelling above" no further data is required for insulation or thickness.',SRC.B2(22)),
Q('Roofs','What age band is assumed for a room in roof with no documentary evidence of a new age?',['The same as the main building','The conversion date','Post 2002','1990s'],0,'The age band of the room in roof is assumed the same as the main building when there is no documentary evidence.',SRC.B2(26)),

/* ---------- Floors ---------- */
Q('Floors','A stamp test gives a hollow, shaky effect. What floor type is it?',['Suspended timber or suspended concrete','Solid','Floor to external air','Basement floor'],0,'Suspended floors give a hollow effect and normally have an air brick. Solid floors feel rigid.',SRC.B2(32)),
Q('Floors','Which is the most common floor insulation option?',['As built','Retro-fitted','Unknown','Mineral wool'],0,'As built is most common and is used in the absence of valid information.',SRC.B2(33)),
Q('Floors','When can "retro-fitted" floor insulation be selected?',['If insulation is present and confirmed by observation or documents','Always','If the floor is solid','If the house is pre-1930'],0,'Only if insulation is present and can be confirmed by DEA observation or documentary evidence.',SRC.B2(33)),
Q('Insulation','Why should "unknown" insulation be avoided?',['It automatically suppresses insulation recommendations','It increases the EPC rating','It requires a second visit','It is not available in the software'],0,'Unknown insulation automatically suppresses any insulation recommendation, so use it only in exceptional situations.',SRC.B2(36)),

/* ---------- Age bands ---------- */
Q('Age bands','Which age band covers most UK houses (about 40%)?',['1930s to 1949','1950s to 1966','1970s','1900 to 1929'],0,'The 1930s to 1949 band is where 40% of UK houses fit.',SRC.B2(42)),
Q('Age bands','What age band applies when a heated commercial building, such as a school, is converted to homes?',['The original construction age of the building','The date of conversion','Post 2002','Unknown'],0,'Use the original age of construction. Specify upgraded elements where visual or documentary evidence is available.',SRC.B2(47)),
Q('Age bands','What age band applies when an unheated building, such as a barn, is converted to a home?',['The conversion age','The original construction age','1900 to 1929','The age of the neighbouring houses'],0,'For unheated buildings (barn, train station) select the conversion age.',SRC.B2(48)),
Q('Age bands','From which year did local authorities begin providing the age and date of buildings (via the Planning Portal)?',['1972','1948','1990','2008'],0,'Local authorities started to provide age and date of buildings from 1972.',SRC.B2(44)),
Q('Age bands','Why did steel frame, system built homes appear in the 1950s to 1966 band?',['Left-over steel from the war was used','Timber was banned','Concrete was unavailable','Cavity walls were banned'],0,'Steel frame, system built construction used left-over steel from the war.',SRC.B2(43)),

/* ---------- Heating ---------- */
Q('Heating','Which of these is a sign of a combination (combi) boiler?',['No separate hot water cylinder','Only three metal pipes entering the boiler','No audible firing when a hot tap is turned on','A single thermostat only'],0,'Signs: more pipes (5 or 6), an audible "firing" when a hot tap is on, no separate cylinder, and dual thermostats for hot water and heating.',SRC.B3(6)),
Q('Heating','A cylinder is present with a combi boiler. How do you enter it?',['Combi as Main 1 and a generic regular boiler as Main 2 with 0% floor area','Combi as Main 1 only','Two combis','As an electric immersion'],0,'Select the combi as Main Heating 1 and a generic regular boiler as Main Heating 2 with 0% floor area served by space heating. This allows the cylinder details to be input.',SRC.B3(6)),
Q('Heating','How is micro CHP recorded if there is no PCDF reference?',['As a gas condensing boiler','As a heat pump','As a warm air system','As an electric boiler'],0,'Micro CHP can only be recorded via the PCDF. If no PCDF reference is available, enter it as a gas condensing boiler.',SRC.B3(27)),
Q('Heating','A CPSU is on a single electric tariff. How should it be entered?',['As a direct acting electric boiler','As a CPSU','As a storage heater','As a heat pump'],0,'A CPSU uses a 10 or 18 hour tariff with a dual meter. On a single tariff, enter it as a direct acting electric boiler.',SRC.B3(24)),
Q('Heating','Which is a sign of an electric direct acting boiler?',['No gas pipe and no flue pipe outside','A flue terminal on the wall','A bulk tank outside','A condensate pipe'],0,'Electricity is the main fuel, with no gas pipe and no external flue pipe.',SRC.B3(25)),
Q('Heating','One boiler feeds underfloor heating downstairs and radiators upstairs. What emitter do you enter?',['Radiators (Convention 4.04)','Underfloor heating','Both','Warm air'],0,'Convention 4.04: if one heating system feeds both underfloor and radiators, enter radiators. This is because radiators need a higher flow temperature.',SRC.B3(31)),
Q('Heating','Without documentary evidence, what do you record for pump age and flow temperature of a boiler?',['Unknown for both','Pump age 5 years, flow 65 °C','Pump age 10 years, flow 55 °C','Leave blank'],0,'In the absence of documentary evidence, record external pump age as unknown and flow temperature as unknown.',SRC.B3(33)),
Q('Heating','Where is the heat generator in a community heating scheme?',['Not in the dwelling','Always in the loft','In the cellar of that dwelling','In an extension'],0,'If the generator is in the dwelling, it is that dwelling\'s heating system. If not, treat it as community heating.',SRC.B3(20)),
Q('Heating','Main system 1 and main system 2 serve the same heating circuit. What is the default floor area split?',['50/50','70/30','100/0','60/40'],0,'Where two systems serve the same heating circuit the default assumption is a 50/50 split, unless there is documentary evidence otherwise.',SRC.B2(50)),
Q('Heating','What does control type "TRVs + programmer + bypass" mean?',['There is no boiler interlock when the TRVs have all closed','There is full zone control','The boiler is condensing','There is a room thermostat only'],0,'With TRVs, programmer and bypass there is no boiler interlock to turn off the boiler when the TRVs have closed.',SRC.B3(16)),
Q('Heating','A central system providing space and water heating is selected as main when it can heat at least what share of the dwelling?',['30%','10%','50%','100%'],0,'Select the system capable of heating at least 30% of the dwelling (habitable rooms only) as the main system.',SRC.B2(49)),
Q('Heating','How can you tell a dual electric meter on a digital display?',['It shows rate 1 and rate 2','It shows a single reading','It has one reading strip','It has a blue button'],0,'Dual meters show rate 1 and rate 2 when scrolling through options. Use "unknown" only when there is no access to the meter.',SRC.B3(29)),

/* ---------- Ventilation ---------- */
Q('Ventilation','What is the minimum diameter of an "open chimney" in RDSAP 10?',['200 mm','100 mm','150 mm','300 mm'],0,'Open chimneys are vertical ducts of 200 mm diameter or greater. Chimneys with a damper are also open chimneys.',SRC.B3(35)),
Q('Ventilation','How is a chimney with a damper fitted classed?',['An open chimney','A blocked chimney','A closed fire flue','Ignored'],0,'New clarification: chimneys fitted with a damper are considered open chimneys.',SRC.B3(35)),
Q('Ventilation','Open flues are vertical ducts of what diameter?',['Less than 200 mm','200 mm or more','Exactly 300 mm','Any diameter'],0,'Open flues are vertical ducts with a diameter of less than 200 mm.',SRC.B3(35)),
Q('Ventilation','How big can the vent in a blocked chimney be before it is counted as an open flue?',['Larger than 10 cm × 30 cm','Larger than 5 cm × 5 cm','Larger than 20 cm × 20 cm','Any vent size'],0,'A blocked chimney vent must be no larger than 10 cm × 30 cm (30,000 mm²). Larger than that, record it as an open flue.',SRC.B3(37)),
Q('Ventilation','An extractor fan in a kitchen only filters and recirculates air. Is it counted?',['No, it must extract air to the outside','Yes','Only if in the kitchen','Only if on a light switch'],0,'Ensure the fan extracts air to the outside. Units that only filter and recirculate do not count.',SRC.B3(37)),
Q('Ventilation','Flues in an unheated garage or outside the heated part of the dwelling are…',['Not counted','Counted as open flues','Counted as blocked chimneys','Counted twice'],0,'Only flues located within the heated part of the dwelling should be counted.',SRC.B3(35)),
Q('Ventilation','A mechanical ventilation system with a single central fan serving several rooms is…',['Centralised','Decentralised','Passive stack','Intermittent'],0,'Centralised systems serve multiple rooms through a single central fan unit ("whole house"). Decentralised systems use separate room fans.',SRC.B3(40)),
Q('Ventilation','What is passive stack ventilation?',['Non-mechanical ventilation using natural convection through ceiling ducts','A fan system with heat recovery','An extractor in the kitchen','A trickle vent'],0,'Passive stack ventilation is a non-mechanical system using natural convection and air currents to remove stale air through ceiling-mounted ducts.',SRC.B3(38)),
Q('Ventilation','What evidence can be used to enter an air permeability value?',['Certification evidence only','Householder\'s estimate','The assessor\'s judgement','Photographs'],0,'Only certification evidence can be used to provide an air permeability value.',SRC.B3(41)),

/* ---------- Hot water and lighting ---------- */
Q('Hot water','A cylinder has a dual immersion heater but only a single electric meter. How is it entered?',['Single immersion','Dual immersion','Off-peak immersion','Instantaneous'],0,'If a dual immersion heater is on a single electric meter, enter it as a single immersion.',SRC.B3(43)),
Q('Hot water','What size is a normal cylinder?',['90 to 130 litres','131 to 170 litres','Over 170 litres','Under 90 litres'],0,'Normal is 90 to 130 litres, medium is 131 to 170 litres and large is over 170 litres. Two or three bedroom dwellings default to 110 litres.',SRC.B3(44)),
Q('Hot water','A separate boiler provides hot water only. How is it recorded?',['As Main Heating 2 with 0% heating allocated','As a secondary heater','As an immersion heater','It is ignored'],0,'A separate boiler for hot water only is recorded as second main heating with 0% heating allocated, so it is assigned to hot water only.',SRC.B3(48)),
Q('Hot water','Below what cylinder volume can the water volume be ignored for an electric point-of-use heater?',['55 litres','110 litres','25 litres','90 litres'],0,'Ignore the water volume if it is less than 55 litres.',SRC.B3(47)),
Q('Lighting','In RDSAP, light bulbs are referred to as…',['Lamps','Luminaires','Fittings','Outlets'],0,'Terms such as "light bulb", "bulb" and "light" are all referred to as a "lamp".',SRC.B3(49)),
Q('Lighting','Which lighting outlets are counted?',['Fixed (hard-wired) outlets only','All lamps, including table lamps','Outdoor lights only','Only LED lamps'],0,'Only fixed lighting outlets, hard-wired into the property, should be counted.',SRC.B3(50)),
Q('Lighting','Are traditional fluorescent tubes counted with CFLs?',['Yes','No, they are incandescent','No, they are LEDs','They are excluded'],0,'Traditional fluorescent tubes are included in the CFL count.',SRC.B3(50)),
Q('Lighting','Which is NOT counted as low energy lighting?',['Low voltage halogen lights','LED lamps','Compact fluorescent lamps','Fluorescent tubes'],0,'Low voltage halogen and mains voltage halogen lights are not low energy. Portable fittings and external lights are not counted at all.',SRC.B3(51)),

/* ---------- Portfolio checklist ---------- */
Q('Professional practice','How long is a lodged EPC valid?',['10 years or until a subsequent EPC is lodged','5 years','15 years','1 year'],0,'Lodged EPCs are retained on a national database and are valid for 10 years or until a subsequent EPC is lodged.',SRC.CL(2)),
Q('Professional practice','Who can access a lodged EPC?',['Anybody','Only the owner','Only the assessor','Only local authorities'],0,'Lodged EPCs are retained on a national database and can be accessed by anybody.',SRC.CL(2)),
Q('Professional practice','For how long should assessment documentation be securely stored?',['15 years','5 years','10 years','1 year'],0,'Records should be securely stored for 15 years, in line with Data Protection Legislation. They are treated as a legal document.',SRC.CL(2)),
Q('Professional practice','Within how many days should a client complaint be resolved?',['21 days','7 days','14 days','90 days'],0,'The complaint will be addressed via email or telephone and resolved within 21 days.',SRC.CL(2)),
Q('Professional practice','If the internal complaints procedure does not resolve the issue, who is engaged?',['An independent panel of three individuals with no direct involvement','The client\'s solicitor','The local council only','The assessor\'s employer'],0,'An Independent Panel comprising three individuals without direct involvement or interest in the decision will be engaged.',SRC.CL(3)),
Q('Professional practice','If a client is dissatisfied with the resolution of a complaint, it is escalated to…',['The Accreditation Scheme','Trading Standards only','The local authority','The estate agent'],0,'The complaint is elevated to the Accreditation Scheme without affecting legal rights, and is documented and accessible to the scheme.',SRC.CL(2)),
Q('Professional practice','Which circumstances may prevent an energy assessment going ahead?',['The property is a new build, or health and safety reasons','The weather is cold','The client is not at home','The property is more than 50 years old'],0,'The instruction letter must explain that the assessment may be prevented where the property is a new build or for health and safety reasons.',SRC.CL(1))
];
